# Generated by Django 3.1.4 on 2021-02-03 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='membership',
            field=models.BooleanField(default=False),
        ),
    ]
