# Generated by Django 3.1.4 on 2021-02-01 13:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='cancel_at_period_end',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='membership',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='stripe_subscription_id',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='stripeid',
        ),
    ]
