# Generated by Django 3.1.4 on 2021-02-08 11:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='stripeid',
            new_name='stripe_customer_id',
        ),
    ]
