# Generated by Django 3.1.4 on 2021-01-27 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='cancel_at_period_end',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='membership',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='stripe_subscription_id',
            field=models.CharField(default=False, max_length=255),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='stripeid',
            field=models.CharField(default=False, max_length=255),
        ),
    ]
