# Generated by Django 3.1.4 on 2021-02-03 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_userprofile_membership'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='cancel_at_period_end',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='stripe_subscription_id',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='stripeid',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
