# Generated by Django 3.1.4 on 2021-02-09 10:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_auto_20210208_1139'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='stripe_customer_id',
            new_name='stripeid',
        ),
    ]
