# Generated by Django 3.1.4 on 2021-02-23 15:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0003_auto_20210209_1019'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='stripeid',
            new_name='stripe_customer_id',
        ),
    ]
