# Generated by Django 3.1.4 on 2021-04-16 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='order_fulfilled',
            field=models.BooleanField(default=True),
        ),
    ]
