# Generated by Django 3.1.4 on 2021-01-21 14:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='firstname',
            new_name='first_name',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='surname',
            new_name='second_name',
        ),
    ]
