# Generated by Django 3.1.4 on 2021-04-16 09:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0002_auto_20210416_0935'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='order_fulfilled',
        ),
    ]
