# Generated by Django 3.1.4 on 2021-01-29 12:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0001_initial'),
        ('checkout', '0002_subscriptionorderlineitem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscriptionorderlineitem',
            name='subscription',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='subscriptions.subscription'),
        ),
    ]
