# Generated by Django 3.1.4 on 2021-01-21 16:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0002_auto_20210121_1441'),
    ]

   
