# Generated by Django 3.1.4 on 2021-02-19 13:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0002_order_payment_recurring'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='payment_recurring',
        ),
    ]
