# Generated by Django 3.1.4 on 2021-02-01 11:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0003_auto_20210129_1247'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subscriptionorderlineitem',
            old_name='subscription',
            new_name='plan',
        ),
    ]
