# Generated by Django 3.1.4 on 2021-04-16 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0003_remove_order_order_fulfilled'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='order_fulfilled',
            field=models.BooleanField(default=True, null=True),
        ),
    ]
