# Generated by Django 3.1.4 on 2021-02-01 12:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0004_auto_20210201_1138'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subscriptionorderlineitem',
            name='quantity',
        ),
    ]
