# Generated by Django 3.1.4 on 2021-02-01 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0005_remove_subscriptionorderlineitem_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriptionorderlineitem',
            name='quantity',
            field=models.IntegerField(default=0),
        ),
    ]
