# Generated by Django 3.1.4 on 2021-02-01 12:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0006_subscriptionorderlineitem_quantity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subscriptionorderlineitem',
            name='quantity',
        ),
    ]
