# Generated by Django 3.1.4 on 2021-02-03 12:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('checkout_plans', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='plancustomer',
            name='membership',
        ),
    ]
