# Generated by Django 3.1.4 on 2021-01-27 13:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='SubscriptionPlan',
            new_name='RecipeSubscription',
        ),
        migrations.RenameField(
            model_name='recipesubscription',
            old_name='user_subscribed',
            new_name='premium',
        ),
    ]
