# Generated by Django 3.1.4 on 2021-02-01 11:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0004_auto_20210201_1138'),
        ('subscriptions', '0002_auto_20210129_1335'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Subscription',
            new_name='SubscriptionPlan',
        ),
    ]
