# Generated by Django 3.1.4 on 2021-02-01 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0003_auto_20210201_1138'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriptionplan',
            name='premium',
            field=models.BooleanField(default=True),
        ),
    ]
