# Generated by Django 3.1.4 on 2021-02-01 13:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_auto_20210201_1306'),
        ('subscriptions', '0004_subscriptionplan_premium'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubscriptionCustomer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stripeid', models.CharField(default=False, max_length=255)),
                ('stripe_subscription_id', models.CharField(default=False, max_length=255)),
                ('cancel_at_period_end', models.BooleanField(default=False)),
                ('membership', models.BooleanField(default=False)),
                ('user_profile', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subscriptions', to='profiles.userprofile')),
            ],
        ),
    ]
