# Generated by Django 3.1.4 on 2021-01-27 15:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0004_subscription'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='SubscriptionRecipes',
            new_name='SubscriptionRecipe',
        ),
    ]
