# Generated by Django 3.1.4 on 2021-02-01 14:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0005_subscriptioncustomer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subscriptionplan',
            name='price',
        ),
    ]
