# Generated by Django 3.1.4 on 2021-02-01 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0006_remove_subscriptionplan_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriptionplan',
            name='price',
            field=models.DecimalField(decimal_places=2, default=10.99, max_digits=6),
            preserve_default=False,
        ),
    ]
