# Generated by Django 3.1.4 on 2021-02-24 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingredient',
            name='unit_of_measurement_choices',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
