# Generated by Django 3.1.4 on 2021-02-10 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0002_remove_recipe_premium'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipe',
            name='text',
        ),
        migrations.AddField(
            model_name='recipe',
            name='ingredients',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='recipe',
            name='recipe_text',
            field=models.TextField(blank=True, null=True),
        ),
    ]
