# Generated by Django 3.1.4 on 2021-02-24 12:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0002_ingredient_unit_of_measurement_choices'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ingredient',
            old_name='unit_of_measurement_choices',
            new_name='unit_of_measurement',
        ),
    ]
