# Generated by Django 3.1.4 on 2021-02-10 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0003_auto_20210210_1528'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='image_url',
            field=models.URLField(blank=True, max_length=1024, null=True),
        ),
    ]
