# Generated by Django 3.1.4 on 2021-02-10 17:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0006_auto_20210210_1632'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recipe',
            old_name='recipe_text',
            new_name='instructions',
        ),
    ]
