# Generated by Django 3.1.4 on 2021-02-10 17:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0008_auto_20210210_1736'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ingredient',
            options={'verbose_name_plural': 'Recipes'},
        ),
    ]
