# Generated by Django 3.1.4 on 2021-02-10 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0010_auto_20210210_1739'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='ingredient_list',
            field=models.ManyToManyField(blank=True, related_name='ingredient_list', to='recipes.Ingredient'),
        ),
    ]
