# Generated by Django 3.1.4 on 2021-02-10 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0011_auto_20210210_1744'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='ingredient_list',
            field=models.ManyToManyField(related_name='ingredient_list', to='recipes.Ingredient'),
        ),
    ]
