# Generated by Django 3.1.4 on 2021-02-12 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0013_remove_ingredient_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='added_date',
            field=models.DateTimeField(blank=True),
        ),
    ]
