# Generated by Django 3.1.4 on 2021-02-15 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0014_auto_20210212_1358'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingredient',
            name='friendly_name',
            field=models.CharField(blank=True, max_length=254, null=True),
        ),
    ]
