# Generated by Django 3.1.4 on 2021-02-15 15:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0015_ingredient_friendly_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ingredient',
            name='friendly_name',
        ),
    ]
