# Generated by Django 3.1.4 on 2021-02-15 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0016_remove_ingredient_friendly_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='added_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
