# Generated by Django 3.1.4 on 2021-03-04 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_product_inventory'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='inventory_updated',
            field=models.BooleanField(default=False),
        ),
    ]
