# Generated by Django 3.1.4 on 2021-03-04 17:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_product_inventory_updated'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='has_colours',
        ),
    ]
